version: "3"

networks:
  corp-nx:
    driver: bridge
services:
  ms-cache:
    container_name: cache
    networks:
      - corp-nx
    restart: always
    build:
      context: .
      dockerfile: cicd/api/Dockerfile
      args:
        - APP=cache
    environment:
      - PORT=3000
    ports:
      - 5000:3000
    depends_on:
      - cache
  cache:
    image: redis:latest
    container_name: cache_redis
    networks:
      - corp-nx
    ports:
      - 6379:6379
  mydb:
    image: mysql
    container_name: mydb
    networks:
      - corp-nx 
    restart: always
    environment:
      MYSQL_DATABASE: monorepo
      MYSQL_ALLOW_EMPTY_PASSWORD: ok
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: monorepo
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3306:3306'
    expose:
      - "3306"      
    volumes:
      - ./local-resources/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql      
